# Generated by Django 6.0.5 on 2026-05-27 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(blank=True, choices=[('Work Visa', 'Work Visa'), ('Student Visa', 'Student Visa'), ('Permanent Residency', 'Permanent Residency'), ('PNP', 'Provincial Nominee Program'), ('Express Entry', 'Express Entry'), ('Asylum', 'Asylum')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
