# Generated by Django 6.0.5 on 2026-05-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('minimum_crs', models.IntegerField(blank=True, null=True)),
                ('processing_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
