# Generated by Django 6.0.5 on 2026-06-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_immigrationstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrationstream',
            name='stream_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
