# Generated by Django 6.0.5 on 2026-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_immigrationstream_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='immigrationstream',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
